services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./nats:/data
    command: ["-js", "-sd", "/data"]
  wasmcloud:
    depends_on:
      - "nats"
    image: wasmcloud/wasmcloud:latest
    environment:
      RUST_LOG: debug,hyper=info,async_nats=info,oci_client=info,cranelift_codegen=warn
      WASMCLOUD_LOG_LEVEL: debug
      WASMCLOUD_RPC_HOST: nats
      WASMCLOUD_CTL_HOST: nats
    ports:
      - "8080:8080" # HTTP
      - "4223:4223"
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    volumes:
      - ./surrealdb:/surrealdb
    command: ["start", "--log", "info", "--user", "root", "--pass", "root", "--bind", "0.0.0.0:8000", "rocksdb:/surrealdb/database.db"]




  marketplace-frontend:
    depends_on:
      - "nats"
      - "wasmcloud"
      - "surrealdb"
    build:
      context: ./marketplace/website
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5173:5173" # Svelte dev server
      - "6006:6006" # Storybook
    develop:
      watch:
        - path: ./marketplace/website/Dockerfile
          action: rebuild
        - path: ./marketplace/website/docker-entrypoint.sh
          action: rebuild
        - path: ./marketplace/website/package.json
          action: rebuild
        - path: ./marketplace/website/packege-lock.json
          action: rebuild
        - path: ./marketplace/website/components.json
          target: /app/components.json
          action: sync+restart
        - path: ./marketplace/website/eslint.config.js
          target: /app/eslint.config.js
          action: sync+restart
        - path: ./marketplace/website/vite.config.js
          target: /app/vite.config.js
          action: sync+restart
        - path: ./marketplace/website/tsconfig.json
          target: /app/tsconfig.json
          action: sync+restart
        - path: ./marketplace/website/svelte.config.js
          target: /app/svelte.config.js
          action: sync+restart
        - path: ./marketplace/website/postcss.config.js
          target: /app/postcss.config.js
          action: sync+restart
        - path: ./makerplace/website/tailwind.config.ts
          target: /app/tailwind.config.ts
          action: sync
        - path: ./marketplace/website/src/
          target: /app/src
          action: sync
        - path: ./marketplace/website/static/
          target: /app/static
          action: sync
        - path: ./marketplace/website/.storybook/
          target: /app/.storybook
          action: sync
