name = "surrealdb-component"
language = "rust"
type = "component"

[component]
wasm_target = "wasm32-wasip2"

[registry.pull]
sources = [
    { target = "seamlezz:surrealdb", source = "file://../wit/world.wit" },
]
