services:
  registry:
    image: registry:2.8
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5001
    ports:
      - "5001:5001"
  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_API_ADDR: http://vault:8200
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: http://vault:8200
      VAULT_LOG_LEVEL: debug
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

  nats:
    image: nats:2.11-alpine
    ports:
      - "4222:4222"
      - "4223:4223"
      - "6222:6222"
      - "8222:8222"
    environment:
      ENCRYPTION_XKEY_SEED: SXAOMQ7V3E4D2JTHGJ7DNUUATHQ6TRYTTW7JC4XR6P55VFJMNPPA6CYZSQ
      TRANSIT_XKEY_SEED: SXAJRAJFLHXFTGMSQDVNNAA7DFAQ65TZJLL5ZYIQKNPM5AD3PV5QMG54GU
    volumes:
      - ./nats:/data
      - ./nats-server.conf:/etc/nats/nats-server.conf:ro
      - ./resolver.conf:/etc/nats/resolver.conf:ro
    command: ["-config", "/etc/nats/nats-server.conf"]
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      start_period: 3s
      retries: 3
      timeout: 3s
      interval: 14s

  secrets-vault:
    image: ghcr.io/wasmcloud/contrib/secrets-vault
    depends_on:
      vault:
        condition: service_healthy
      nats:
        condition: service_healthy
    environment:
      SV_NATS_ADDRESS: nats://nats:4222
      SV_JWKS_ADDRESS: 0.0.0.0:3456
      SV_SERVER_NKEY_SEED: SXAOMQ7V3E4D2JTHGJ7DNUUATHQ6TRYTTW7JC4XR6P55VFJMNPPA6CYZSQ
      SV_SERVER_XKEY_SEED: SXAJRAJFLHXFTGMSQDVNNAA7DFAQ65TZJLL5ZYIQKNPM5AD3PV5QMG54GU
      SV_VAULT_ADDRESS: http://vault:8200
      SV_VAULT_AUTH_METHOD: jwt
      SV_VAULT_DEFAULT_SECRET_ENGINE: secret
      SV_NATS_JWT: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiI0QUtOS1JURkZCR1FTWVJSQ1lVN1YyNkFZMlNIUFAySEFWVFhWNE41UlhITjVFVE4zNTRBIiwiaWF0IjoxNzQ1NzI4MDM0LCJpc3MiOiJBQlU2SFRaTEpETUU3TFBHU0xBVkdNSjJXS0Y1TUlOQzZKTlRIR0JLMlFKRzJRNjVKUkU0VEFOUSIsIm5hbWUiOiJ3YXNtY2xvdWQiLCJzdWIiOiJVQVNKVFVJT0tGWU1CNklGRUVETjdGTURUUFlBWUw0QjVLNVlNT1FLMllSTTJJQk5TSUVQSUJEVSIsIm5hdHMiOnsicHViIjp7fSwic3ViIjp7fSwic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiaXNzdWVyX2FjY291bnQiOiJBQ05BWVZJQVZNQ0FVU0c1NUg2WUhXT0dRVlUzQUhNRVoyNFBYNVVPMkEyNkYzTUZBSVFSM0dGSyIsInR5cGUiOiJ1c2VyIiwidmVyc2lvbiI6Mn19.weoQo4WJpaSt33wEFe9Nv37d8TNqK-k6VkQgiGe3UbZlWi990SwYgOk9J9mwwlei6vK2eKogOInxY2PLwgrEDg
      SV_NATS_SEED: SUADJWVMIVBGVBRGAAVQDLPAQQREXNXRVCHLJ22UW3J6JL3LX2CIM3CRHA
    ports:
      - "3456:3456"
    # healthcheck:
    #   test: wget http://localhost:3456/.well-known/jwks -q -S -O -
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 15s

  vault-setup:
    image: hashicorp/vault:latest
    depends_on:
      vault:
        condition: service_healthy
      secrets-vault:
        condition: service_started
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./vault/docker-entrypoint-initvault.d/:/docker-entrypoint-initvault.d/
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: "root"
    entrypoint: ["/docker-entrypoint.sh"]


  wasmcloud:
    depends_on:
      registry:
        condition: service_started
      nats:
        condition: service_healthy
      secrets-vault:
        condition: service_started
    image: wasmcloud/wasmcloud:latest
    environment:
      RUST_LOG: debug,hyper=info,async_nats=info,oci_client=info,cranelift_codegen=warn,opentelemetry-http=info
      WASMCLOUD_LOG_LEVEL: debug
      WASMCLOUD_NATS_HOST: nats 
      WASMCLOUD_NATS_CREDS: /app/wasmcloud.creds
      WASMCLOUD_SECRETS_TOPIC: wasmcloud.secrets
      WASMCLOUD_OCI_ALLOWED_INSECURE: registry:5001
      WASMCLOUD_OBSERVABILITY_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:4318"
      WASMCLOUD_OBSERVABILITY_PROTOCOL: "http"
      ENCRYPTION_XKEY_SEED: SXAOMQ7V3E4D2JTHGJ7DNUUATHQ6TRYTTW7JC4XR6P55VFJMNPPA6CYZSQ
      TRANSIT_XKEY_SEED: SXAJRAJFLHXFTGMSQDVNNAA7DFAQ65TZJLL5ZYIQKNPM5AD3PV5QMG54GU
    volumes:
      - ./wasmcloud.creds:/app/wasmcloud.creds
    ports:
      - "10000-11000:10000-11000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wadm:
    depends_on:
      nats:
        condition: service_healthy
      secrets-vault:
        condition: service_started
    image: ghcr.io/wasmcloud/wadm:latest
    environment:
      # RUST_LOG: debug,hyper=info,async_nats=info,oci_client=info,cranelift_codegen=warn,opentelemetry-http=info
      RUST_LOG: info
      WADM_NATS_SERVER: nats
      WADM_NATS_CREDS_FILE: /app/wasmcloud.creds
    volumes:
      - ./wasmcloud.creds:/app/wasmcloud.creds

  developer-watcher:
    build:
      context: ./developer-watcher
      dockerfile: Dockerfile
    depends_on:
      - "wadm"
      - "wasmcloud"
    volumes:
      - ../backend:/app/backend
      - ./wasmcloud.creds:/app/wasmcloud.creds
    environment:
      WDEV_PROJECTS_BASE_DIR: /app/backend
      WASH_NATS_HOST: nats
      WASH_NATS_PORT: 4222
      WASH_REGISTRY: registry:5001
      WASH_REGISTRY_INSECURE: true
      WASMCLOUD_CTL_HOST: nats
      WASMCLOUD_CTL_PORT: 4222
      WDEV_DEBOUNCE_MS: 1000
      RUST_LOG: info
      ENCRYPTION_XKEY_SEED: SXAOMQ7V3E4D2JTHGJ7DNUUATHQ6TRYTTW7JC4XR6P55VFJMNPPA6CYZSQ
      TRANSIT_XKEY_SEED: SXAJRAJFLHXFTGMSQDVNNAA7DFAQ65TZJLL5ZYIQKNPM5AD3PV5QMG54GU
    develop:
      watch:
        - path: ./developer-watcher/Dockerfile
          action: rebuild
        - path: ./developer-watcher/Cargo.toml
          action: rebuild
        - path: ./developer-watcher/src/
          action: rebuild
    restart: unless-stopped

