[package]
name = "organizations-component"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
surrealdb-component = { version = "0", registry = "seamlezz" }
wasmcloud-component = "0.2.0"
