apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: organizations
  annotations:
    version: v0.0.1
    description: 'A way to request all the companies a user has access to'
spec:
  policies:
    - name: vault
      type: policy.secret.wasmcloud.dev/v1alpha1
      properties:
        backend: 'vault'
        role_name: 'wasmcloud-role'
        mount_path: 'jwt'
  components:
    - name: organizations-component
      type: component
      properties:
        image: registry:5001/organizations_component:0.1.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: surrealdb-provider
            namespace: seamlezz
            package: surrealdb
            interfaces: [call]
        - type: link
          properties:
            target:
              name: nats
              secrets:
                - name: client_jwt
                  properties:
                    policy: vault
                    key: nats/auth/typewriter
                    field: jwt
                    version: '1'
                - name: client_seed
                  properties:
                    policy: vault
                    key: nats/auth/typewriter
                    field: seed
                    version: '1'
              config:
                - name: organizations-consumer
                  properties:
                    cluster_uris: 'nats://nats:4222'
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.27.0
      traits:
        - type: link
          properties:
            target:
              name: organizations-component
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source:
              secrets:
                - name: client_jwt
                  properties:
                    policy: vault
                    key: nats/auth/typewriter
                    field: jwt
                    version: '1'
                - name: client_seed
                  properties:
                    policy: vault
                    key: nats/auth/typewriter
                    field: seed
                    version: '1'
              config:
                - name: subscription
                  properties:
                    subscriptions: 'user.*.organization.list'
                    cluster_uris: 'nats://nats:4222'
    - name: surrealdb-provider
      type: capability
      properties:
        image: registry:5001/surrealdb_provider:0.1.0 
        config:
          - name: auth-typewriter-permissions-surrealdb
            properties:
              namespace: typewriter
              database: develop
              auth: root
              username: root
              password: root
              url: ws://surrealdb:9000


