name: typewriter_panel
description: "The panel to configure all of Typewriter"
publish_to: 'none'
version: 1000.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^3.0.0-dev.15
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^3.0.0-dev.15
  auto_route: ^10.0.1
  logto_dart_sdk: ^3.0.0
  localstorage: ^6.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dart_nats: ^0.6.5
  rive: ^0.13.20
  collection: 
  iconify_flutter_plus: ^1.0.4
  responsive_framework: ^1.5.1
  flutter_animate: ^4.5.2
  mocktail: ^1.0.4
  dart_casing: ^3.0.1
  okcolor: ^1.1.0
  url_launcher: ^6.3.1
  flutter_context_menu: ^0.2.4
  uuid: ^4.5.1
  dotted_border: ^3.1.0
  collapsible: ^1.0.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: 
  build_runner: 
  custom_lint: 
  riverpod_lint: 
  flutter_lints: 
  auto_route_generator: 
  icons_launcher: 
  freezed: 
  json_serializable:

icons_launcher:
  image_path: "assets/typewriter_app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-VariableFont_wght.ttf
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Italic-VariableFont_wght.ttf
          style: italic

