apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: auth-callout
  annotations:
    version: v0.0.1
    description: 'Authorization callout for NATS'
spec:
  policies:
    - name: vault
      type: policy.secret.wasmcloud.dev/v1alpha1
      properties:
        backend: 'vault'
        role_name: 'wasmcloud-role'
        mount_path: 'jwt'
  components:
    - name: auth-callout-component
      type: component
      properties:
        image: registry:5001/auth_callout_component:0.1.0
        config:
          - name: auth-config
            properties:
              issuers: '[{"id":"typewriter","issuer_url":"https://auth.typewritermc.com/oidc","jwks_url":"https://auth.typewritermc.com/oidc/jwks", "nats_account_key": "AAOGRKTAIDHPREVFTNK7AB6RZPWEAQ7CLWPZWGTHOBZCNULC4H2KMJ5J"}]'
        secrets:
          - name: nats-issuer-seed
            properties:
              policy: vault
              key: nats/auth-callout/issuer
              field: seed
              version: '1'
          - name: nats-signing-keys
            properties:
              policy: vault
              key: nats/auth-callout/signing-keys
              version: '1'
      traits:
        - type: spreadscaler
          properties:
            instances: 100
        - type: link
          properties:
            target:
              name: nats
              secrets:
                - name: client_jwt
                  properties:
                    policy: vault
                    key: nats/auth/callout
                    field: jwt
                    version: '1'
                - name: client_seed
                  properties:
                    policy: vault
                    key: nats/auth/callout
                    field: seed
                    version: '1'
              config:
                - name: provider-tgt
                  properties:
                    cluster_uris: 'nats://nats:4222'
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
        - type: link
          properties:
            target:
              name: httpclient
            namespace: wasi
            package: http
            interfaces: [outgoing-handler]

    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.27.0
      traits:
        - type: link
          properties:
            target:
              name: auth-callout-component
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source:
              secrets:
                - name: client_jwt
                  properties:
                    policy: vault
                    key: nats/auth/callout
                    field: jwt
                    version: '1'
                - name: client_seed
                  properties:
                    policy: vault
                    key: nats/auth/callout
                    field: seed
                    version: '1'
              config:
                - name: auth-callout-subscription
                  properties:
                    subscriptions: '$SYS.REQ.USER.AUTH'
                    cluster_uris: 'nats://nats:4222'
    - name: httpclient
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-client:0.13.1
