name: Deploy Documentation

on:
  push:
    branches:
      - develop
    paths:
      - "documentation/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false  # Skip submodules to avoid the git error
          
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('documentation/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Cache documentation node modules
        uses: actions/cache@v4
        with:
          path: documentation/node_modules
          key: ${{ runner.os }}-docs-node-${{ hashFiles('documentation/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-docs-node-
            
      - name: Cache Docusaurus build folder
        uses: actions/cache@v4
        with:
          path: documentation/.docusaurus
          key: ${{ runner.os }}-docusaurus-${{ hashFiles('documentation/**/*.md', 'documentation/**/*.mdx', 'documentation/docusaurus.config.js') }}
          restore-keys: |
            ${{ runner.os }}-docusaurus-
            
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: documentation/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./documentation
        
      - name: Build website
        run: npm run build
        working-directory: ./documentation
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          
      - name: Add CNAME
        run: echo "docs.typewritermc.com" > ./documentation/build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./documentation/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
